baseURL = 'localhost:8080'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
homeText = "Sample site from scratch"
dateFormat = "Jan 2, 2006"

[permalinks]
blog = "/:filename/"

[taxonomies]
tag = "tags"

[menu]
[[menu.main]]
name = "Home"
pre = "home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
pre = "edit"
url = "/blog"
weight = 2
[[menu.main]]
name = "Tags"
pre = "tag"
url = "/tags"
weight = 3